title: <center>Max Paterson</center>
logo: /images/Profilepic.jpg

description: | 
Data Science and Analyst Portfolio 
<br><br> 
Please Contact for Resume 
<br> 
Phone Number: (403) 471-3115 
<br> 
Email: Max.r.paterson@gmail.com
<a href="https://www.linkedin.com/in/maxwellpaterson/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
github:
  is_project_page: false
classes: wide
